import type { Metadata } from "next";
import { Gabarito, Neuton } from "next/font/google";
import "./globals.css";
import { CharacterContextProvider } from "./context/CharacterContext";

const gabarito = Gabarito({
  subsets: ["latin"],
  weight: ["400", "800"],
});

const neuton = Neuton({
  subsets: ["latin"],
  weight: ["800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={gabarito.className}>
        <CharacterContextProvider>{children}</CharacterContextProvider>
      </body>
    </html>
  );
}
